CREATE TABLE painters (
  artistName text,
  url text,
  wikipediaUrl text,
  deathDay date,
  contentId integer PRIMARY KEY,
  deathDayAsString text,
  birthDayAsString text,
  birthDay date,
  lastNameFirst text,
  image text,
  dictonaries integer[]
)

CREATE TABLE pictures (
  serie text,
  diameter real,
  sizeX real,
  yearOfTrade integer,
  artistName text,
  location text,
  artistUrl text,
  contentId integer PRIMARY KEY,
  lastPrice real,
  period text,
  technique text,
  width integer,
  title text,
  artistContentId integer REFERENCES painters(contentId),
  material text,
  style text,
  completitionYear integer,
  sizeY real,
  height integer,
  galleryName text,
  description text,
  tags text,
  yearAsString text,
  genre text,
  image text,
  dictionaries integer[],
  auction text,
  url text
)